// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3qKFTsc1foFzgw-O1f0P1nej5-vWrmjw',
    appId: '1:465876269736:web:f273776ddbaf15d34ba09d',
    messagingSenderId: '465876269736',
    projectId: 'portfolio-b8b5f',
    authDomain: 'portfolio-b8b5f.firebaseapp.com',
    storageBucket: 'portfolio-b8b5f.appspot.com',
    measurementId: 'G-QM2FMSGRWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfAXqjlxUCO1vjlplPAOyqf42SHt3LPf0',
    appId: '1:465876269736:android:1ff73303ac103fbe4ba09d',
    messagingSenderId: '465876269736',
    projectId: 'portfolio-b8b5f',
    storageBucket: 'portfolio-b8b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEiaWNW3yIvdlbyDKh25vCOkq4P9IEZ0w',
    appId: '1:465876269736:ios:fa56cc86c22437f54ba09d',
    messagingSenderId: '465876269736',
    projectId: 'portfolio-b8b5f',
    storageBucket: 'portfolio-b8b5f.appspot.com',
    iosBundleId: 'com.example.venkatesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEiaWNW3yIvdlbyDKh25vCOkq4P9IEZ0w',
    appId: '1:465876269736:ios:fa56cc86c22437f54ba09d',
    messagingSenderId: '465876269736',
    projectId: 'portfolio-b8b5f',
    storageBucket: 'portfolio-b8b5f.appspot.com',
    iosBundleId: 'com.example.venkatesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3qKFTsc1foFzgw-O1f0P1nej5-vWrmjw',
    appId: '1:465876269736:web:be8caaf4c1b75c594ba09d',
    messagingSenderId: '465876269736',
    projectId: 'portfolio-b8b5f',
    authDomain: 'portfolio-b8b5f.firebaseapp.com',
    storageBucket: 'portfolio-b8b5f.appspot.com',
    measurementId: 'G-CTXM7XY7KP',
  );
}
